### ISSUE TITLE
Performances

### ISSUE THREAD

**Issue by wenjun90** [poodarchu/DETR.detectron2#1]
Hi,
Congratulation for your good job.

I would like to ask you the performance that you get? mAP and FPS?

Thank!

**Comment by poodarchu** [comment]
stay tuned, I'll release results in a few days.

**Comment by poodarchu** [comment]
> Hi,
> Congratulation for your good job.
> 
> I would like to ask you the performance that you get? mAP and FPS?
> 
> Thank!

It can be used now.

**Comment by wenjun90** [comment]
Thanks @poodarchu ,
Waiting new results from you :)
