### ISSUE TITLE
target["image_id"] should allow string or integer

### ISSUE THREAD

**Issue by benqua** [poodarchu/DETR.detectron2#5]
## Instructions To Reproduce the 🐛 Bug:
Trying to train DETR model with a custom dataset where image_id is a string throws an exception `TypeError: new(): invalid data type 'str'` at [line 173 of detr.py](https://github.com/poodarchu/DETR.detectron2/blob/master/projects/DETR/detr.py#L173).

## Expected behavior:
In detectron2, the field 'image_id' can be [a string or a int](https://detectron2.readthedocs.io/tutorials/datasets.html), the DETR model should accept both to be compatible with detectron2 datasets.

## Other
Thanks for your work!
Will you try to submit it to the official detectron2 repository?

**Comment by poodarchu** [comment]
1. You can check your custom dataset’s image I’d type. In COCO, image is is of type integer.
2. I’lol not push to detectron2

**Comment by benqua** [comment]
I know that in COCO, image_id is an integer.
I was just mentioning that if you want your DETR model implementation to be compatible with detectron2, it should accept detectron2 dataset format.

Thank you for your reply.
